name: radio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  just_audio: ^0.9.32
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
